version: "3.8"

services:
  api-gateway:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    networks:
      - api-gateway
    ports:
      - "8080:8080"

networks:
  api-gateway:
    driver: bridge
